site_name: 100 Go Mistakes and How to Avoid Them
site_url: https://100go.co
repo_name: teivah/100-go-mistakes
theme:
  name: material
  custom_dir: overrides
  favicon: img/Go-Logo_LightBlue.svg
  language: en
  logo: img/Go-Logo_White.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - search.share
    - search.suggest
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: cyan
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue grey
repo_url: https://github.com/teivah/100-go-mistakes
plugins:
  - search
  - social:
      cards_layout_options:
        logo: img/cover.png
extra:
  analytics:
    provider: google
    property: G-HMY1HYDM93
  alternate:
    - name: English
      link: /
      lang: en
    - name: Chinese (Simplified)
      link: /zh/
      lang: zh
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/teivah
    - icon: fontawesome/brands/medium
      link: http://blog.teivah.io
nav:
    - Book:
        - book.md
        - chapter-1.md
        - external.md
    - Go Mistakes:
      - index.md
      - Full Sections:
        - 9-generics.md
        - 98-profiling-execution-tracing.md
      - zh.md
    - ❤️ Go Jobs:
      - jobs.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
copyright: Copyright &copy; 2022 - 2023 Teiva Harsanyi
