site_name: 100 Go Mistakes
site_url: https://100go.co
theme:
  name: material
  custom_dir: overrides
  favicon: Go-Logo_Fuchsia.svg
  language: en
  logo: Go-Logo_Fuchsia.svg
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: cyan
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue grey
repo_url: https://github.com/teivah/100-go-mistakes
plugins:
  - search
  - social
extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Chinese (Simplified)
      link: /chinese/
      lang: zh
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/teivah
  generator: false

